export const MANAUS_NEIGHBORHOODS_TO_ZONES = {
  // Zona Norte
  "Águas Claras": "Zona Norte",
  "Boas Novas": "Zona Norte",
  "Campo Dourado": "Zona Norte",
  "Carlos Braga": "Zona Norte",
  "Cidade de Deus": "Zona Norte",
  "Cidade Nova": "Zona Norte",
  "Núcleo 1": "Zona Norte",
  "Núcleo 2": "Zona Norte",
  "Núcleo 3": "Zona Norte",
  "Núcleo 4": "Zona Norte",
  "Núcleo 5": "Zona Norte",
  "Núcleo 6": "Zona Norte",
  "Núcleo 7": "Zona Norte",
  "Núcleo 8": "Zona Norte",
  "Núcleo 9": "Zona Norte",
  "Núcleo 10": "Zona Norte",
  "Núcleo 11": "Zona Norte",
  "Núcleo 12": "Zona Norte",
  "Núcleo 13": "Zona Norte",
  "Núcleo 14": "Zona Norte",
  "Núcleo 15": "Zona Norte",
  "Núcleo 16": "Zona Norte",
  "Núcleo 17": "Zona Norte",
  "Núcleo 18": "Zona Norte",
  "Núcleo 19": "Zona Norte",
  "Núcleo 20": "Zona Norte",
  "Núcleo 21": "Zona Norte",
  "Núcleo 22": "Zona Norte",
  "Núcleo 23": "Zona Norte",
  "Núcleo 24": "Zona Norte",
  "Colônia Santo Antônio": "Zona Norte",
  "Colônia Terra Nova": "Zona Norte",
  "Fazendinha": "Zona Norte",
  "Francisca Mendes": "Zona Norte",
  "Galileia": "Zona Norte",
  "Jesus Me Deu": "Zona Norte",
  "João Paulo": "Zona Norte",
  "Lago Azul": "Zona Norte",
  "Manoa": "Zona Norte",
  "Monte das Oliveiras": "Zona Norte",
  "Mundo Novo": "Zona Norte",
  "Mutirão": "Zona Norte",
  "Nossa Senhora de Fátima": "Zona Norte",
  "Nova Cidade": "Zona Norte",
  "Novo Aleixo": "Zona Norte",
  "Novo Israel": "Zona Norte",
  "Omar Aziz": "Zona Norte",
  "Oswaldo Frota": "Zona Norte",
  "Renato Souza Pinto": "Zona Norte",
  "Riacho Doce": "Zona Norte",
  "Ribeiro Júnior": "Zona Norte",
  "Santa Etelvina": "Zona Norte",
  "Viver Melhor": "Zona Norte",
  "Viver Melhor I": "Zona Norte",
  "Viver Melhor II": "Zona Norte",
  "Viver Melhor III": "Zona Norte",
  "Viver Melhor IV": "Zona Norte",
  "Canaranas": "Zona Norte",
  "Vila Real": "Zona Norte",

  // Zona Leste
  "Acariquara": "Zona Leste",
  "Armando Mendes": "Zona Leste",
  "Bairro Novo": "Zona Leste",
  "Braga Mendes": "Zona Leste",
  "Castanheiras": "Zona Leste",
  "Cidade Leste": "Zona Leste",
  "Colônia Antônio Aleixo": "Zona Leste",
  "Coroado": "Zona Leste",
  "Distrito Industrial II": "Zona Leste",
  "Gilberto Mestrinho": "Zona Leste",
  "Grande Vitória": "Zona Leste",
  "João Bosco": "Zona Leste",
  "João Paulo II": "Zona Leste",
  "Jorge Teixeira": "Zona Leste",
  "Mauazinho": "Zona Leste",
  "Monte Sião": "Zona Leste",
  "Nova Floresta": "Zona Leste",
  "Nova Vitória": "Zona Leste",
  "Ouro Verde": "Zona Leste",
  "Puraquequara": "Zona Leste",
  "São José Operário": "Zona Leste",
  "Tancredo Neves": "Zona Leste",
  "Val Paraíso": "Zona Leste",
  "Zumbi dos Palmares": "Zona Leste",

  // Zona Sul
  "Betânia": "Zona Sul",
  "Cachoeirinha": "Zona Sul",
  "Cajual": "Zona Sul",
  "Centro": "Zona Sul",
  "Colônia Oliveira Machado": "Zona Sul",
  "Crespo": "Zona Sul",
  "Distrito Industrial I": "Zona Sul",
  "Educandos": "Zona Sul",
  "Japiim": "Zona Sul",
  "Japiinlândia": "Zona Sul",
  "Manaus 2000": "Zona Sul",
  "Morro da Liberdade": "Zona Sul",
  "Nossa Senhora de Aparecida": "Zona Sul",
  "Panair": "Zona Sul",
  "Petrópolis": "Zona Sul",
  "Praça 14 de Janeiro": "Zona Sul",
  "Presidente Vargas": "Zona Sul",
  "Matinha": "Zona Sul",
  "Raiz": "Zona Sul",
  "Santa Luzia": "Zona Sul",
  "São Benedito": "Zona Sul",
  "São Francisco": "Zona Sul",
  "São Lázaro": "Zona Sul",
  "Vila Buriti": "Zona Sul",

  // Zona Centro-Sul
  "Adrianópolis": "Zona Centro-Sul",
  "Aleixo": "Zona Centro-Sul",
  "Bairro da União": "Zona Centro-Sul",
  "Beija-Flor": "Zona Centro-Sul",
  "Chapada": "Zona Centro-Sul",
  "Conjunto Castelo Branco": "Zona Centro-Sul",
  "Conjunto Tocantins": "Zona Centro-Sul",
  "Eldorado": "Zona Centro-Sul",
  "Flores": "Zona Centro-Sul",
  "Morada do Sol": "Zona Centro-Sul",
  "Nossa Senhora das Graças": "Zona Centro-Sul",
  "Parque 10 de Novembro": "Zona Centro-Sul",
  "Parque 10": "Zona Centro-Sul",
  "Parque das Laranjeiras": "Zona Centro-Sul",
  "São Geraldo": "Zona Centro-Sul",
  "Shangrillá": "Zona Centro-Sul",
  "Tiradentes": "Zona Centro-Sul",
  "Vieiralves": "Zona Centro-Sul",

  // Zona Oeste
  "Campos Sales": "Zona Oeste",
  "Compensa": "Zona Oeste",
  "Conjunto Cophasa": "Zona Oeste",
  "Glória": "Zona Oeste",
  "Lírio do Vale": "Zona Oeste",
  "Marina do Davi": "Zona Oeste",
  "Nova Esperança": "Zona Oeste",
  "Parque das Tribos": "Zona Oeste",
  "Parque Riachuelo": "Zona Oeste",
  "Parque São Pedro": "Zona Oeste",
  "Ponta Negra": "Zona Oeste",
  "Santo Agostinho": "Zona Oeste",
  "Santo Antônio": "Zona Oeste",
  "São Jorge": "Zona Oeste",
  "São Raimundo": "Zona Oeste",
  "Tarumã": "Zona Oeste",
  "Tarumã-Açu": "Zona Oeste",
  "Vila da Prata": "Zona Oeste",
  "Vila Marinho": "Zona Oeste",
  "Vivenda do Pontal": "Zona Oeste",

  // Zona Centro-Oeste
  "Ajuricaba": "Zona Centro-Oeste",
  "Alvorada": "Zona Centro-Oeste",
  "Alvorada I": "Zona Centro-Oeste",
  "Alvorada II": "Zona Centro-Oeste",
  "Alvorada III": "Zona Centro-Oeste",
  "Bairro da Paz": "Zona Centro-Oeste",
  "Belvedere": "Zona Centro-Oeste",
  "Campos Elíseos": "Zona Centro-Oeste",
  "Dom Pedro": "Zona Centro-Oeste",
  "Dom Pedro I": "Zona Centro-Oeste",
  "Dom Pedro II": "Zona Centro-Oeste",
  "Eduardo Gomes": "Zona Centro-Oeste",
  "Hiléia": "Zona Centro-Oeste",
  "Kíssia": "Zona Centro-Oeste",
  "Planalto": "Zona Centro-Oeste",
  "Promorar": "Zona Centro-Oeste",
  "Redenção": "Zona Centro-Oeste",
  "Santos Dumont": "Zona Centro-Oeste",
  "Tropical": "Zona Centro-Oeste"
};

export const getZoneByNeighborhood = (neighborhood) => {
  if (!neighborhood) return null;
  
  // Normalização para busca insensível a acentos e case
  const normalizedSearch = neighborhood.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  
  const match = Object.keys(MANAUS_NEIGHBORHOODS_TO_ZONES).find(key => {
    const normalizedKey = key.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return normalizedKey === normalizedSearch;
  });

  return match ? MANAUS_NEIGHBORHOODS_TO_ZONES[match] : null;
};
